# Generated by Django 4.1.13 on 2024-04-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
