# Generated by Django 4.1.13 on 2024-04-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
